### ISSUE TITLE
Widget Backend Issue

### ISSUE THREAD

**Issue by Basilakis** [kbrmedia/FreshDesk-Envato#2]
Hello,

I have installed the widget, and with a test call it works correctly, but I can not make it visible at the backend. I have enabled the pug, but seems not to work as ashould. Can you help me out on that please?

**Comment by radykal** [comment]
It seems you also have to run the php script under https, because the backend of freshdesk is also using this protocol. Otherwise you get a [mixed content warning](https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content).

**Comment by kbrmedia** [comment]
@radykal Yes, I confirm this but the script has to be hosted externally. If your domain doesn't have a SSL certificate, alternatively you can directly send a request to Envato's API and then format the code.
